# Generated by Django 4.1 on 2022-08-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default='10', max_length=2)),
                ('create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
