# Generated by Django 4.1 on 2022-08-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_class', '0002_alter_class_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='classDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('session', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('eve', 'EVE')], default='', max_length=4)),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_class.class')),
            ],
            options={
                'unique_together': {('begin', 'end', 'session')},
            },
        ),
    ]
